Repository imn00133/BeerNode, pull requests merged in 2021-02, with the labels that each got.

#27 Beer node 20
  beernode/urls.py
  media/scrap/20191217_114359.jpg
  scraplistapp/templates/scraplistapp/test_home.html
  scraplistapp/views.py
Labels: Front End, enhancement

#31 BeerNode-28 commit convention 문서 추가
  doc/commit_convention.md
Labels: documentation

#32 Added: accountapp에 detailview 추가
  accountapp/templates/accountapp/detail.html
  accountapp/urls.py
  accountapp/views.py
  scraplistapp/templates/scraplistapp/test_home.html
  scraplistapp/urls.py
Labels: Back End, enhancement

#34 Fixed: tes_home.html 위치변경
  beernode/urls.py
  templates/test_home.html
Labels: Back End, enhancement, fix

#36 Feature/beer node 30
  beernode/urls.py
  scrapapp/static/css/detail.css
  scrapapp/templates/scrapapp/create.html
  scrapapp/templates/scrapapp/detail.html
  static/css/base.css
  templates/base.html
  templates/head.html
  templates/header.html
  templates/test_home.html
Labels: Front End, enhancement

#45 BeerNode-41 Django dockerfile생성
  Dockerfile
  media/scrap/20191217_114359.jpg
  requirements.txt
Labels: Infra, enhancement

#47 BeerNode-46 - Completed: imagefield 비어있는 상태로 제출 가능하게 변경
  scrapapp/migrations/0003_auto_20210210_2020.py
  scrapapp/models.py
Labels: Back End, fix

#48 BeerNode-38 - Completed: 마신날짜 추가
  scrapapp/forms.py
  scrapapp/migrations/0004_scrap_date.py
  scrapapp/models.py
Labels: Back End, fix

#49 Beer node 43
  node_modules/magic-grid/.eslintrc.js
  node_modules/magic-grid/CONTRIBUTING.md
  node_modules/magic-grid/LICENSE
  node_modules/magic-grid/README.md
  node_modules/magic-grid/dist/magic-grid.cjs.js
  node_modules/magic-grid/dist/magic-grid.esm.js
  node_modules/magic-grid/dist/magic-grid.min.js
  node_modules/magic-grid/index.d.ts
  node_modules/magic-grid/package.json
  node_modules/magic-grid/rollup.config.js
  node_modules/magic-grid/src/index.js
  node_modules/magic-grid/src/utils.js
  node_modules/magic-grid/test/grid-element.html
  node_modules/magic-grid/test/grid.html
  package-lock.json
  scraplistapp/static/javascript/magicgrid.js
  scraplistapp/templates/scraplistapp/list_block.html
  scraplistapp/templates/scraplistapp/list_oneline.html
Labels: Back End, enhancement

#59 BeerNode-55 dev, prod환경 env분리
  ReadMe.md
  beernode/settings.py
  dev.dockerfile
  manage.py
  prod.dockerfile
Labels: Back End, Infra, enhancement

#60 Feature/beer node 13
  accountapp/decorators.py
  accountapp/templates/accountapp/delete.html
  accountapp/templates/accountapp/detail.html
  accountapp/urls.py
  accountapp/views.py
Labels: Back End, enhancement

#71 BeerNode-62 Fixed: scraplistapp - context, create app 미표시 문제 해결
  scraplistapp/templates/scraplistapp/list.html
Labels: enhancement, fix

#72 BeerNode-68 Fixed: Scrap 삭제 시 Scraplist의 Index가 그대로 남아있는 버그 수정
  scraplistapp/templates/scraplistapp/list.html
Labels: enhancement, fix

#73 BeerNode-64 Added: header에 user 표시하기
  templates/header.html
  templates/test_home.html
Labels: enhancement

#78 BeerNode-77 - Added: Block형 list에 해당 사진 출력
  scraplistapp/templates/scraplistapp/list.html
  scraplistapp/urls.py
  templates/snippets/card_blocklist.html
Labels: Back End, enhancement

#79 BeerNode-50 - Fixed: 사진없을 시 detail, test에서 발생한 오류 수정
  scrapapp/templates/scrapapp/detail.html
  templates/snippets/card_blocklist.html
Labels: Back End, fix

#95 BeerNode-80 - Completed: date 위젯 설정 완료
  scrapapp/forms.py
Labels: Front End, enhancement

#96 BeerNode-84 Added: accountapp UpdateView 작성
  accountapp/forms.py
  accountapp/templates/accountapp/detail.html
  accountapp/templates/accountapp/update.html
  accountapp/urls.py
  accountapp/views.py
Labels: Back End, enhancement

#97 BeerNode-85 Added: Scrap Update, Delete 보안 기능 추가
  scrapapp/decorators.py
  scrapapp/templates/scrapapp/detail.html
  scrapapp/views.py
Labels: Back End, Front End, enhancement
