Repository imn00133/BeerNode, pull requests merged in 2021-05, with the labels that each got.

#205 BeerNode-199 scrapapp get_absolute_url 구현
  django/scrapapp/models.py
  django/scrapapp/views.py
Labels: DataBase, enhancement

#210 BeerNode-206 Fixed: Profile app get_absolute_url 구현
  django/profileapp/models.py
  django/profileapp/views.py
Labels: Back End, enhancement

#211 Beer node 175 Added: Beerapp - model 작성
  django/beerapp/__init__.py
  django/beerapp/admin.py
  django/beerapp/apps.py
  django/beerapp/migrations/0001_initial.py
  django/beerapp/migrations/0002_auto_20210513_1732.py
  django/beerapp/migrations/__init__.py
  django/beerapp/models.py
  django/beerapp/templates/beerapp/detail.html
  django/beerapp/tests.py
  django/beerapp/urls.py
  django/beerapp/views.py
  django/beernode/settings.py
  django/beernode/urls.py
  django/profileapp/migrations/0005_auto_20210512_2127.py
  django/profileapp/migrations/0006_auto_20210512_2129.py
Labels: Back End, DataBase, enhancement

#212 Beernode-178 - Completed: listapp 완성
  django/beernode/settings.py
  django/beernode/urls.py
  django/feedapp/__init__.py
  django/feedapp/admin.py
  django/feedapp/apps.py
  django/feedapp/filters.py
  django/feedapp/migrations/__init__.py
  django/feedapp/models.py
  django/feedapp/tests.py
  django/feedapp/urls.py
  django/feedapp/views.py
  django/listapp/__init__.py
  django/listapp/admin.py
  django/listapp/apps.py
  django/listapp/forms.py
  django/listapp/migrations/0001_initial.py
  django/listapp/migrations/0002_auto_20210204_0146.py
  django/listapp/migrations/0003_scraplist_scrap.py
  django/listapp/migrations/__init__.py
  django/listapp/models.py
  django/listapp/static/javascript/magicgrid.js
  django/listapp/templates/listapp/list.html
  django/listapp/templates/listapp/list_block.html
  django/listapp/templates/listapp/list_oneline.html
  django/listapp/tests.py
  django/listapp/urls.py
  django/listapp/views.py
  django/scrapapp/models.py
  django/scrapapp/views.py
  django/scraplistapp/forms.py
  django/scraplistapp/models.py
  django/scraplistapp/templates/scraplistapp/list_block.html
  django/scraplistapp/urls.py
  django/scraplistapp/views.py
  django/templates/snippets/card_blocklist.html
  django/templates/test_home.html
Labels: Back End, enhancement

#213 Beernode-154 - Profileapp과 Listapp을 Feedapp으로 병합
  django/accountapp/templates/accountapp/detail.html
  django/feedapp/templates/feedapp/feed.html
  django/feedapp/urls.py
  django/feedapp/views.py
  django/listapp/templates/listapp/list.html
  django/templates/header.html
Labels: Back End, Front End, enhancement

#218 Beer node 166
  django/listapp/templates/listapp/list.html
  django/scraplistapp/views.py
  django/templates/snippets/pagination.html
Labels: Back End, enhancement

#219 Beer node 171 - Scrap detail - 맛 관련 코드 압축하기
  django/scrapapp/templates/scrapapp/detail_table.html
  django/scrapapp/views.py
Labels: Front End, enhancement, fix

#220 Beer node 166
  django/feedapp/templates/feedapp/feed.html
  django/feedapp/views.py
  django/listapp/templates/listapp/list.html
  django/templates/snippets/card_blocklist.html
  django/templates/snippets/pagination.html
Labels: Back End, enhancement, fix

#226 BeerNode-166 - Completed: filter를 위한 get_queryset설정 및 filter출력
  django/feedapp/views.py
Labels: Back End, DataBase, enhancement
