Repository imn00133/BeerNode, pull requests merged in 2021-01, with the labels that each got.

#6 BeerNode-5 - Completed: base.html 작성
  templates/base.html
Labels: Front End, enhancement

#8 scrap app create form 작성
  beernode/settings.py
  beernode/urls.py
  scrap/KakaoTalk_20200310_214504931.jpg
  scrapapp/__init__.py
  scrapapp/admin.py
  scrapapp/apps.py
  scrapapp/forms.py
  scrapapp/migrations/0001_initial.py
  scrapapp/migrations/0002_scrap_picture.py
  scrapapp/migrations/__init__.py
  scrapapp/models.py
  scrapapp/templates/scrapapp/create.html
  scrapapp/tests.py
  scrapapp/urls.py
  scrapapp/views.py
Labels: Back End, enhancement

#11 BeerNode-10 - Completed: PR test
  templates/base.html
Labels: Front End, enhancement

#22 Feature/scrapapp detailview
  beernode/settings.py
  scrapapp/models.py
  scrapapp/templates/scrapapp/detail.html
  scrapapp/urls.py
  scrapapp/views.py
  templates/base.html
Labels: Back End, enhancement, fix

#25 BeerNode-24 - Added: django-bootstrap4 및 Pillow 환경설정 추가
  ReadMe.md
Labels: Back End, bug, fix
