Repository imn00133/BeerNode, pull requests merged in 2021-03, with the labels that each got.

#106 Beernode-63 - Completed: Scraplist와 User 연결 기능 구현
  .gitignore
  django/beernode/settings.py
  django/scrapapp/views.py
  django/scraplistapp/templates/scraplistapp/list.html
  django/scraplistapp/urls.py
  django/scraplistapp/views.py
  django/templates/test_home.html
Labels: Back End, enhancement

#112 Beernode-111 - Improved: Scraplist의 block 형태에서 사진이 잘리는 문제 해결
  django/templates/snippets/card_blocklist.html
Labels: Front End

#115 BeerNode-111 - Fixed: scrap create view에서 지도 검색시 페이지 reload 방지
  django/scrapapp/templates/scrapapp/map.html
Labels: Back End, fix

#117 BeerNode-104 - Added: list 출력 페이지에 scrap create 추가
  django/scrapapp/migrations/0009_merge_20210308_2105.py
  django/scraplistapp/templates/scraplistapp/list.html
Labels: Back End, enhancement, fix

#118 BeerNode-103 - Fixed: 한글패치
  django/accountapp/templates/accountapp/detail.html
  django/profileapp/templates/profileapp/create.html
  django/profileapp/templates/profileapp/update.html
  django/scrapapp/templates/scrapapp/create_form.html
  django/scrapapp/templates/scrapapp/delete.html
  django/scrapapp/templates/scrapapp/detail.html
  django/scrapapp/templates/scrapapp/update.html
  django/scraplistapp/templates/scraplistapp/list.html
  django/scraplistapp/templates/scraplistapp/list_oneline.html
  django/templates/header.html
  django/templates/snippets/card_blocklist.html
  django/templates/test_home.html
Labels: Back End, fix

#123 BeerNode-122 - Fixed: create 불가 현상 수정
  django/scrapapp/templates/scrapapp/create_form.html
Labels: Back End, bug, fix

#129 Beernode-100 - Completed: Django-filter 설정 완료
  django/beernode/settings.py
  django/scrapapp/migrations/0010_auto_20210308_2246.py
  django/scraplistapp/filters.py
  django/scraplistapp/templates/scraplistapp/list.html
  django/scraplistapp/templates/scraplistapp/list_block.html
  django/scraplistapp/templates/scraplistapp/list_oneline.html
  django/scraplistapp/views.py
  requirements.txt
Labels: Back End, enhancement

#130 Beer node 88 Scrapapp 맛 항목 추가
  django/scrapapp/forms.py
  django/scrapapp/migrations/0011_auto_20210310_2114.py
  django/scrapapp/migrations/0011_merge_20210312_0248.py
  django/scrapapp/migrations/0012_merge_20210312_0253.py
  django/scrapapp/migrations/0013_auto_20210312_0259.py
  django/scrapapp/models.py
  django/scrapapp/static/css/detail.css
  django/scrapapp/static/rating.png
  django/scrapapp/templates/scrapapp/create_form.html
  django/scrapapp/templates/scrapapp/detail.html
  django/scrapapp/widgets.py
Labels: Back End, Front End, enhancement

#131 BeerNode-114 Changed: Scrap rating.png 이미지 변경
  django/scrapapp/static/css/detail.css
  django/scrapapp/static/rating.png
Labels: Front End, fix

#132 Beer node 114
  django/scrapapp/static/css/detail.css
Labels: Front End, fix

#135 BeerNode-12 7User 설정 및 media 설정 / python PEP8 맞추기
  django/accountapp/forms.py
  django/accountapp/urls.py
  django/accountapp/views.py
  django/beernode/urls.py
  django/profileapp/forms.py
  django/profileapp/models.py
  django/profileapp/urls.py
  django/profileapp/views.py
  django/scrapapp/decorators.py
  django/scrapapp/forms.py
  django/scrapapp/urls.py
  django/scrapapp/views.py
  django/scrapapp/widgets.py
  django/scraplistapp/filters.py
  django/scraplistapp/forms.py
  django/scraplistapp/models.py
  django/scraplistapp/urls.py
Labels: Back End, enhancement

#139 Beernode-121 - DefaultStaticImageField 적용
  django/beernode/settings.py
  django/beernode/urls.py
  django/scrapapp/fields.py
  django/scrapapp/models.py
  django/scrapapp/templates/scrapapp/detail.html
  django/templates/snippets/card_blocklist.html
Labels: Back End, enhancement

#140 Beer node 102 : account/profile - account create시 동시에 생성되도록 변경
  django/accountapp/forms.py
  django/accountapp/templates/accountapp/create.html
  django/accountapp/templates/accountapp/detail.html
  django/accountapp/views.py
  django/profileapp/forms.py
  django/profileapp/migrations/0003_auto_20210316_1839.py
  django/profileapp/models.py
  django/scrapapp/migrations/0014_auto_20210316_1617.py
Labels: Back End, Front End, enhancement

#142 BeerNode-141 Fixed: debug_toolbar duplicate 문제 해결
  django/beernode/settings.py
  django/scrapapp/migrations/0015_auto_20210316_2110.py
Labels: Back End, bug

#144 Beernode-141 - Fixed: debug_toolbar duplicate 문제 해결
  django/beernode/settings.py
Labels: bug, fix

#145 Beernode-99 - Completed: 액세스가 거부되는 경우 메인화면으로 redirect
  django/scrapapp/decorators.py
  django/templates/403.html
Labels: Back End, Front End, fix

#147 BeerNode-146 - Fixed: migrations 파일 재정비
  django/scrapapp/migrations/0014_auto_20210318_1416.py
  django/scrapapp/migrations/0015_auto_20210316_2110.py
Labels: Back End, bug, fix

#149 BeerNode-116 - Fixed: create view css 적용 시도
  django/scrapapp/templates/scrapapp/create_form.html
Labels: Front End, fix

#151 BeerNode-133 - Fixed: element 밖으로 내용이 튀어나오는 것 수정
  django/scrapapp/templates/scrapapp/detail_map.html
  django/scrapapp/templates/scrapapp/detail_table.html
  django/scrapapp/views.py
Labels: Front End, fix

#152 Beer node 148
  django/scrapapp/templates/scrapapp/detail.html
  django/scrapapp/templates/scrapapp/detail_table.html
Labels: Back End, enhancement

#158 Beernode-121 - Fixed: django_fields 제거, fields.py를 이용하여 default image 설정
  django/scrapapp/fields.py
  django/scrapapp/migrations/0014_auto_20210318_1416.py
  django/scrapapp/models.py
Labels: Back End, Front End, fix

#159 Beer node 136 scrap app - pk 내 내용이 존재하지 않을 때 redirect
  django/templates/404.html
Labels: Back End, enhancement, fix

#160 BeerNode-134 - Added: 스케일바 조정 시 실시간 숫자 표시 + 시각화
  django/scrapapp/templates/scrapapp/create_form.html
Labels: Front End, enhancement

#161 Beer node 150 detail에서 context 공백 처리
  django/scrapapp/templates/scrapapp/detail.html
  django/scrapapp/templates/scrapapp/detail_table.html
Labels: Front End, fix

#163 BeerNode-156: account 생성 후, nickname 설정하도록 redirection
  django/accountapp/templates/accountapp/detail.html
  django/accountapp/views.py
  django/profileapp/forms.py
  django/profileapp/migrations/0003_auto_20210328_1855.py
  django/profileapp/models.py
  django/profileapp/templates/profileapp/create.html
Labels: Back End, enhancement

#164 BeerNode-128 - Completed: django-extensions 설치
  django/beernode/settings.py
  requirements.txt
Labels: Back End, enhancement

#168 Beernode-167 - Profileapp에 default image 적용
  django/accountapp/templates/accountapp/detail.html
  django/default_image/__init__.py
  django/default_image/fields.py
  django/profileapp/migrations/0004_auto_20210331_1509.py
  django/profileapp/models.py
  django/scrapapp/migrations/0014_auto_20210318_1416.py
  django/scrapapp/models.py
Labels: Back End, enhancement
